[package]
name = "image-loading"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { workspace = true }
anyhow = { workspace = true }
image = { workspace = true, features = ["jpeg", "png", "webp"] }
env_logger = "0.11.7"
log = "0.4.26"
